name: CI Build and Test Trade Matching Engine

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Install dependencies on Ubuntu
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # Step 3: Install dependencies on Windows
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install mingw -y

      # Step 4: Configure the build with CMake
      - name: Configure with CMake
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cmake -S . -B build -G "MinGW Makefiles"
          else
            cmake -S . -B build
          fi
        shell: bash

      # Step 5: Build the project
      - name: Build with CMake
        run: |
          cmake --build build

      # Step 6: Run tests with ctest
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
